FROM ubuntu:22.04


RUN apt-get update && apt-get install -y \
    iputils-ping \
    python3 \
    python3-pip \
    net-tools \
    curl \
    wget \
    vim \
    git \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /app

RUN pip install celery numpy matplotlib aiohttp

COPY primes.json client.py celery_worker.py ./